In [1]:
import torch

In [2]:
# 초기화되지 않은 5x3 행렬 생성하기

x = torch.empty(5, 3)
print(x)

tensor([[1.0653e-38, 1.0194e-38, 8.4490e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39]])


In [3]:
# 무작위로 초기화된 행렬 생성하기

x = torch.rand(5, 3)
print(x)

tensor([[0.4871, 0.0296, 0.8652],
        [0.1766, 0.2242, 0.9541],
        [0.1308, 0.7295, 0.4894],
        [0.1296, 0.7274, 0.9093],
        [0.4801, 0.3368, 0.0130]])


In [12]:
# dtype이 logn이고 0으로 채워진 행렬을 생성하기

x1 = torch.zeros(5, 3, dtype=torch.long)
print(x1)
print()

x2 = torch.zeros(5, 3, 2, dtype=torch.long)
print(x2)
print()

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]])



In [13]:
# 데이터로부터 tensor를 직접 생성하기

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [34]:
# 존재하는 tensor를 바탕으로 tensor 만들기
# 이 메소드들은 사용자로부터 제공된 새로운 값이 없는한, 입력 tensor의 속성들(예. dtype)을 재사용한다.
first = torch.rand(5, 3)

x1 = first.new_ones(5, 3, dtype=torch.double)  # new_* 메소드는 크기를 받는다.
print(x1)
print("first's dtype: ", first.dtype)
print("x1's dtype: ", x1.dtype)
print()

x2 = torch.randn_like(first, dtype=torch.float)  # dtype을 오버라이드(Override) 한다
print(x2)  # 결과는 동일한 크기
print()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
first's dtype:  torch.float32
x1's dtype:  torch.float64

tensor([[-0.5836,  1.1725,  0.1872],
        [ 0.6518, -1.5275,  0.6557],
        [-0.8890, -1.0717,  0.8255],
        [-1.1542,  0.0907, -0.6982],
        [-0.1601, -0.2328,  0.1649]])



In [36]:
# 행렬의 크기 구하기

print(x2.size())

torch.Size([5, 3])
