# Pytorch

In [1]:
import torch

## tensor

In [2]:
# 초기화되지 않은 5x3 행렬 생성하기

x = torch.empty(5, 3)
print(x)

tensor([[1.0653e-38, 1.0194e-38, 8.4490e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39]])


In [3]:
# 무작위로 초기화된 행렬 생성하기

x = torch.rand(5, 3)
print(x)

tensor([[0.4871, 0.0296, 0.8652],
        [0.1766, 0.2242, 0.9541],
        [0.1308, 0.7295, 0.4894],
        [0.1296, 0.7274, 0.9093],
        [0.4801, 0.3368, 0.0130]])


In [12]:
# dtype이 logn이고 0으로 채워진 행렬을 생성하기

x1 = torch.zeros(5, 3, dtype=torch.long)
print(x1)
print()

x2 = torch.zeros(5, 3, 2, dtype=torch.long)
print(x2)
print()

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]])



In [13]:
# 데이터로부터 tensor를 직접 생성하기

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [34]:
# 존재하는 tensor를 바탕으로 tensor 만들기
# 이 메소드들은 사용자로부터 제공된 새로운 값이 없는한, 입력 tensor의 속성들(예. dtype)을 재사용한다.
first = torch.rand(5, 3)

x1 = first.new_ones(5, 3, dtype=torch.double)  # new_* 메소드는 크기를 받는다.
print(x1)
print("first's dtype: ", first.dtype)
print("x1's dtype: ", x1.dtype)
print()

x2 = torch.randn_like(first, dtype=torch.float)  # dtype을 오버라이드(Override) 한다
print(x2)  # 결과는 동일한 크기
print()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
first's dtype:  torch.float32
x1's dtype:  torch.float64

tensor([[-0.5836,  1.1725,  0.1872],
        [ 0.6518, -1.5275,  0.6557],
        [-0.8890, -1.0717,  0.8255],
        [-1.1542,  0.0907, -0.6982],
        [-0.1601, -0.2328,  0.1649]])



In [36]:
# 행렬의 크기 구하기

print(x2.size())

torch.Size([5, 3])


## 연산(Operations)

In [ ]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [2]:
# 덧셈: 문법 1
print(x + y)

tensor([[1.5166, 0.8686, 0.8824],
        [0.7004, 0.5558, 0.1376],
        [1.0612, 0.7795, 0.7097],
        [1.4036, 0.9720, 0.7216],
        [0.1964, 0.7163, 0.2501]])


In [4]:
# 덧셈: 문법 2
print(torch.add(x, y))

tensor([[1.5166, 0.8686, 0.8824],
        [0.7004, 0.5558, 0.1376],
        [1.0612, 0.7795, 0.7097],
        [1.4036, 0.9720, 0.7216],
        [0.1964, 0.7163, 0.2501]])


In [5]:
# 덧셈: 결과 tensor를 인자로 제공
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.5166, 0.8686, 0.8824],
        [0.7004, 0.5558, 0.1376],
        [1.0612, 0.7795, 0.7097],
        [1.4036, 0.9720, 0.7216],
        [0.1964, 0.7163, 0.2501]])


In [6]:
# 덧셈: 바꿔치기 (in-place) 방식
y.add_(x)
print(y)

# 바꿔치기 (in-place) 방식으로 tensor의 값을 변경하는 연산은
# _ 를 접미사로 갖는다.
# ex) x.copy_(y), x.t_()는 x를 변경한다.

tensor([[1.5166, 0.8686, 0.8824],
        [0.7004, 0.5558, 0.1376],
        [1.0612, 0.7795, 0.7097],
        [1.4036, 0.9720, 0.7216],
        [0.1964, 0.7163, 0.2501]])


In [7]:
# 크기 변경: tensor의 크기(size)나 모양(shape)을 변경한다면 torch.view를 사용

x = torch.randn(4, 4)
print(x)
print()

y = x.view(16)
z = x.view(-1, 8)
print(y)
print(z)
print()

print(x.size(), y.size(), z.size())

tensor([[ 1.5897,  1.1917,  0.8302,  0.3808],
        [-1.5184, -0.1578, -0.5871,  2.0532],
        [-0.9585, -0.7901, -1.3423, -0.2134],
        [-0.0964, -0.4967,  0.3805, -1.0302]])

tensor([ 1.5897,  1.1917,  0.8302,  0.3808, -1.5184, -0.1578, -0.5871,  2.0532,
        -0.9585, -0.7901, -1.3423, -0.2134, -0.0964, -0.4967,  0.3805, -1.0302])
tensor([[ 1.5897,  1.1917,  0.8302,  0.3808, -1.5184, -0.1578, -0.5871,  2.0532],
        [-0.9585, -0.7901, -1.3423, -0.2134, -0.0964, -0.4967,  0.3805, -1.0302]])

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
# 만약 tensor에 하나의 값만 존재한다면, .item()을 사용하여 숫자 값을 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item())
print(x[0])

tensor([1.6734])
1.6734298467636108
tensor(1.6734)


In [14]:
help(torch.rand)

Help on built-in function rand:

rand(...)
    rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
     

In [15]:
help(torch.randn)

Help on built-in function randn:

randn(...)
    randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a normal distribution
    with mean `0` and variance `1` (also called the standard normal
    distribution).
    
    .. math::
        \text{out}_{i} \sim \mathcal{N}(0, 1)
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Def

In [17]:
# numpy 변환 (Bridge)

a = torch.ones(5)
print(a)
print()

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)
print()

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]



In [21]:
# numpy 배열을 torch tensor로 변환하기
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
